//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTWebAPI.Models.Old_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricLogs
    {
        public int MetricLogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MetricID { get; set; }
        public decimal Value { get; set; }
        public System.DateTime CreationTimestamp { get; set; }
    
        public virtual Metric tbl_metrics { get; set; }
        public virtual User tbl_users { get; set; }
    }
}
