//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activites
    {
        public Activites()
        {
            this.tbl_activity_logs = new HashSet<ActivityLogs>();
        }
    
        public int ActivityID { get; set; }
        public string Name { get; set; }
        public decimal CalorieBurnRate { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<ActivityLogs> tbl_activity_logs { get; set; }
    }
}
