//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTEntities : DbContext
    {
        public CTEntities()
            : base("name=CTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activites> Activites { get; set; }
        public virtual DbSet<ActivityLogs> ActivityLogs { get; set; }
        public virtual DbSet<FoodGroup> FoodGroups1 { get; set; }
        public virtual DbSet<FoodLogs> FoodLogs { get; set; }
        public virtual DbSet<FoodNutrientLogs> FoodNutrientLogs { get; set; }
        public virtual DbSet<Food> Foods1 { get; set; }
        public virtual DbSet<MetricLogs> MetricLogs { get; set; }
        public virtual DbSet<Metric> Metrics1 { get; set; }
        public virtual DbSet<NutrientRDA> NutrientRDAs { get; set; }
        public virtual DbSet<Nutrient> Nutrients1 { get; set; }
        public virtual DbSet<User> Users1 { get; set; }
    }
}
