//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        public Metric()
        {
            this.tbl_metric_logs = new HashSet<MetricLogs>();
        }
    
        public int MetricID { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<MetricLogs> tbl_metric_logs { get; set; }
    }
}
